import Link from "next/link";
import { getStockSnapshots } from "@/lib/data/stock-repository";

function money(value: number | null) {
  return value == null ? "—" : `₹${value.toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;
}

const assetCards = [
  ["Stocks", "Research companies, financials, valuation, performance and GNS Score.", "/stocks", "Equities"],
  ["IPOs", "Explore upcoming, open and recently listed public issues.", "/ipo", "Primary market"],
  ["Mutual Funds", "Compare funds, categories, returns, risk and fund characteristics.", "/mutual-funds", "Fund research"],
  ["ETFs", "Explore equity, index, gold, debt and other exchange-traded products.", "/etfs", "Exchange traded"],
  ["Bonds", "Research fixed-income opportunities and compare key bond information.", "/bonds", "Fixed income"],
  ["Markets", "Track indices, market movements, sectors, gainers and losers.", "/markets", "Market pulse"],
] as const;

const workflow = [
  ["01", "Discover", "Find investments across multiple asset classes."],
  ["02", "Screen", "Filter opportunities using the metrics that matter."],
  ["03", "Research", "Understand fundamentals, performance and valuation."],
  ["04", "Compare", "Put investments side-by-side before deciding."],
  ["05", "Decide", "Build a clearer, research-backed investment view."],
] as const;

export default async function HomePage() {
  const stocks = await getStockSnapshots(8);
  const scored = stocks.filter((s) => s.score != null).sort((a, b) => (b.score ?? -1) - (a.score ?? -1));
  const priceDate = stocks.find((s) => s.price_date)?.price_date ?? null;

  return (
    <main className="min-h-screen bg-[#06101d] text-slate-100">
      <nav className="sticky top-0 z-50 border-b border-white/[.07] bg-[#06101d]/90 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-7xl items-center gap-7 px-4 sm:px-6 lg:px-8">
          <Link href="/" className="flex shrink-0 items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-400 font-black text-[#06101d]">G</span><span className="text-lg font-bold tracking-tight">GNSOne</span></Link>
          <div className="hidden items-center gap-5 text-sm text-slate-400 md:flex"><Link href="/markets">Markets</Link><Link href="/stocks">Stocks</Link><Link href="/ipo">IPO</Link><Link href="/mutual-funds">Mutual Funds</Link><Link href="/etfs">ETFs</Link><Link href="/bonds">Bonds</Link><Link href="/screener">Screener</Link><Link href="/compare">Compare</Link></div>
          <div className="ml-auto flex items-center gap-2"><Link href="/stocks" className="hidden rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-300 sm:block">⌕ Search</Link><Link href="/signin" className="rounded-lg border border-white/10 px-4 py-2 text-sm font-medium hover:bg-white/5">Sign in</Link></div>
        </div>
      </nav>

      <section className="relative overflow-hidden border-b border-white/[.06]">
        <div className="pointer-events-none absolute -left-40 top-20 h-96 w-96 rounded-full bg-cyan-400/[.07] blur-3xl" />
        <div className="pointer-events-none absolute -right-24 top-0 h-96 w-96 rounded-full bg-emerald-400/10 blur-3xl" />
        <div className="absolute inset-0 opacity-[.035] [background-image:linear-gradient(rgba(255,255,255,.8)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.8)_1px,transparent_1px)] [background-size:56px_56px]" />
        <div className="relative mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24 lg:px-8 lg:py-28">
          <div className="max-w-4xl">
            <div className="mb-6 inline-flex rounded-full border border-emerald-400/20 bg-emerald-400/[.06] px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[.2em] text-emerald-300">Investment research · Market intelligence</div>
            <h1 className="text-[clamp(2.8rem,8vw,6.7rem)] font-semibold leading-[.94] tracking-[-.055em]">One platform.<br /><span className="text-slate-500">Every investment.</span></h1>
            <p className="mt-7 max-w-2xl text-base leading-7 text-slate-400 sm:text-xl sm:leading-8">Research Stocks, IPOs, Mutual Funds, ETFs and Bonds in one place. Discover opportunities, understand the numbers and compare investments with clarity.</p>
            <Link href="/stocks" className="mt-9 flex max-w-3xl items-center gap-3 rounded-2xl border border-white/10 bg-white/[.045] p-2.5 shadow-2xl shadow-black/20 transition hover:border-emerald-400/30"><span className="px-2 text-xl text-slate-500">⌕</span><span className="flex-1 text-sm text-slate-500 sm:text-base">Search stocks, IPOs, mutual funds, ETFs or bonds...</span><span className="rounded-xl bg-emerald-400 px-5 py-3 text-sm font-bold text-[#06101d]">Explore</span></Link>
            <div className="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-xs text-slate-500"><span>✓ Multi-asset research</span><span>✓ Compare investments</span><span>✓ Explainable analytics</span></div>
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8 lg:py-18">
        <div className="max-w-2xl"><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-emerald-400">Explore the platform</p><h2 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Everything you need to research investments</h2><p className="mt-3 text-sm leading-6 text-slate-400">From listed companies to new issues and fixed income, GNSOne brings different investment categories into one research workspace.</p></div>
        <div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{assetCards.map(([title, description, href, tag], index) => <Link key={title} href={href} className="group rounded-2xl border border-white/[.07] bg-[#0b1727] p-5 transition duration-200 hover:-translate-y-0.5 hover:border-emerald-400/25 hover:bg-[#0d1b2e]"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-white/[.05] text-sm font-bold text-emerald-300">0{index + 1}</span><span className="rounded-full border border-white/[.06] px-2.5 py-1 text-[10px] uppercase tracking-wider text-slate-600">{tag}</span></div><h3 className="mt-7 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p><span className="mt-5 inline-block text-xs font-semibold text-emerald-400">Explore {title} →</span></Link>)}</div>
      </section>

      <section className="border-y border-white/[.06] bg-[#081422]">
        <div className="mx-auto grid max-w-7xl gap-10 px-4 py-14 sm:px-6 lg:grid-cols-[.8fr_1.2fr] lg:px-8 lg:py-18">
          <div><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-slate-500">Why GNSOne</p><h2 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">More than market data.</h2><p className="mt-4 max-w-md text-sm leading-7 text-slate-400">Investing is not only about finding a price. It is about understanding what you are looking at. GNSOne is designed around that research journey.</p></div>
          <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/[.07] bg-[#0b1727] p-5"><h3 className="font-semibold">Discover</h3><p className="mt-2 text-sm leading-6 text-slate-500">Find investments across multiple asset classes from one place.</p></div><div className="rounded-2xl border border-white/[.07] bg-[#0b1727] p-5"><h3 className="font-semibold">Research</h3><p className="mt-2 text-sm leading-6 text-slate-500">Explore fundamentals, performance, valuation and financial data.</p></div><div className="rounded-2xl border border-white/[.07] bg-[#0b1727] p-5"><h3 className="font-semibold">Compare</h3><p className="mt-2 text-sm leading-6 text-slate-500">Put multiple investments side-by-side before making a decision.</p></div><div className="rounded-2xl border border-white/[.07] bg-[#0b1727] p-5"><h3 className="font-semibold">Understand</h3><p className="mt-2 text-sm leading-6 text-slate-500">Turn complex financial information into a clearer research view.</p></div></div>
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8 lg:py-18">
        <div className="mb-8"><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-emerald-400">How it works</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">From discovery to decision.</h2></div>
        <div className="grid gap-3 md:grid-cols-5">{workflow.map(([number, title, description]) => <div key={number} className="relative rounded-2xl border border-white/[.07] bg-[#0b1727] p-5"><span className="text-xs font-bold text-emerald-400">{number}</span><h3 className="mt-6 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p></div>)}</div>
      </section>

      <section className="mx-auto grid max-w-7xl gap-5 px-4 pb-14 sm:px-6 lg:grid-cols-[1.5fr_1fr] lg:px-8 lg:pb-18">
        <div className="overflow-hidden rounded-2xl border border-white/[.07] bg-[#0b1727]"><div className="flex items-center justify-between border-b border-white/[.07] p-5"><div><p className="text-[11px] uppercase tracking-[.18em] text-slate-500">Market workspace</p><h2 className="mt-1 font-semibold">Stocks to research</h2></div><Link href="/stocks" className="text-xs font-semibold text-emerald-400">View all →</Link></div>{stocks.length ? stocks.slice(0, 6).map((stock) => <Link href={`/stocks/${stock.nse_symbol ?? stock.bse_code ?? stock.instrument_id}`} key={stock.instrument_id} className="flex items-center gap-3 border-b border-white/[.05] px-5 py-4 transition hover:bg-white/[.025]"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white/[.05] text-xs font-bold text-slate-300">{stock.name.slice(0, 2).toUpperCase()}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{stock.name}</span><span className="mt-0.5 block text-xs text-slate-500">{stock.nse_symbol ? `NSE · ${stock.nse_symbol}` : `BSE · ${stock.bse_code ?? "—"}`}</span></span><span className="text-right"><span className="block text-sm font-medium">{money(stock.latest_price)}</span><span className="mt-1 block text-[11px] text-slate-600">{stock.price_date ?? "No price"}</span></span>{stock.score != null && <span className="hidden w-12 text-right sm:block"><span className="block text-[9px] uppercase text-slate-600">GNS</span><span className="font-semibold text-emerald-300">{Math.round(stock.score)}</span></span>}</Link>) : <div className="p-10 text-center text-sm text-slate-500">No instruments available yet.</div>}</div>
        <div className="rounded-2xl border border-emerald-400/15 bg-gradient-to-br from-[#0d202b] to-[#0b1727] p-6"><p className="text-[11px] uppercase tracking-[.18em] text-emerald-400">GNS intelligence</p><h2 className="mt-2 text-2xl font-semibold tracking-tight">Understand the signal.</h2><p className="mt-3 text-sm leading-6 text-slate-400">GNS Score brings multiple research factors together so an investment can be viewed beyond a single metric.</p>{scored.length ? <div className="mt-6 space-y-2">{scored.slice(0, 4).map((stock, index) => <Link href={`/stocks/${stock.nse_symbol ?? stock.bse_code ?? stock.instrument_id}`} key={stock.instrument_id} className="flex items-center gap-3 rounded-xl border border-white/[.06] bg-white/[.02] p-3 hover:border-emerald-400/20"><span className="text-xs text-slate-600">0{index + 1}</span><span className="min-w-0 flex-1 truncate text-sm">{stock.name}</span><span className="font-semibold text-emerald-300">{Math.round(stock.score ?? 0)}</span></Link>)}</div> : <div className="mt-6 rounded-xl border border-white/[.06] p-4 text-sm text-slate-500">GNS analytics will appear here as scores become available.</div>}<Link href="/gns-score" className="mt-5 block w-full rounded-xl border border-white/10 py-3 text-center text-sm font-semibold hover:bg-white/5">Explore GNS Score →</Link></div>
      </section>

      <section className="mx-auto max-w-7xl px-4 pb-14 sm:px-6 lg:px-8 lg:pb-18"><div className="rounded-3xl border border-emerald-400/15 bg-gradient-to-br from-[#0d202b] via-[#0b1727] to-[#091522] p-7 sm:p-10 lg:p-14"><div className="max-w-3xl"><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-emerald-400">Research tools</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-5xl">Screen. Compare. Research.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-400 sm:text-base">Build a shortlist with the Screener, compare investments side-by-side and then dive into the underlying research.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/screener" className="rounded-xl bg-emerald-400 px-5 py-3 text-sm font-bold text-[#06101d]">Open Screener</Link><Link href="/compare" className="rounded-xl border border-white/10 px-5 py-3 text-sm font-semibold">Compare investments</Link><Link href="/gns-score" className="rounded-xl border border-white/10 px-5 py-3 text-sm font-semibold">GNS Score</Link></div></div></div></section>

      <section className="border-y border-white/[.06] bg-[#081422]"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-slate-500">Investment insights</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Learn what moves your investments.</h2><p className="mt-3 text-sm leading-6 text-slate-400">Future-ready space for stock analysis, IPO explainers, mutual fund guides, ETF education, bond research and market insights.</p></div><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><div className="rounded-2xl border border-white/[.07] bg-[#0b1727] p-5"><h3 className="font-semibold">Stock Research</h3><p className="mt-2 text-sm text-slate-500">Understand company fundamentals and valuation.</p></div><div className="rounded-2xl border border-white/[.07] bg-[#0b1727] p-5"><h3 className="font-semibold">IPO Guides</h3><p className="mt-2 text-sm text-slate-500">Learn how to evaluate new public issues.</p></div><div className="rounded-2xl border border-white/[.07] bg-[#0b1727] p-5"><h3 className="font-semibold">Fund & ETF Guides</h3><p className="mt-2 text-sm text-slate-500">Understand categories, costs, risk and performance.</p></div></div></div></section>

      <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="grid gap-4 md:grid-cols-4"><div className="rounded-2xl border border-white/[.07] bg-[#0b1727] p-5"><h3 className="font-semibold">Multi-asset</h3><p className="mt-2 text-sm leading-6 text-slate-500">One research workflow across major investment categories.</p></div><div className="rounded-2xl border border-white/[.07] bg-[#0b1727] p-5"><h3 className="font-semibold">Structured data</h3><p className="mt-2 text-sm leading-6 text-slate-500">Financial information organized for easier research.</p></div><div className="rounded-2xl border border-white/[.07] bg-[#0b1727] p-5"><h3 className="font-semibold">Explainable analytics</h3><p className="mt-2 text-sm leading-6 text-slate-500">Scores and metrics presented with context.</p></div><div className="rounded-2xl border border-white/[.07] bg-[#0b1727] p-5"><h3 className="font-semibold">Research first</h3><p className="mt-2 text-sm leading-6 text-slate-500">Built to support informed decisions, not personalized advice.</p></div></div></section>

      <section className="border-t border-white/[.07]"><div className="mx-auto max-w-7xl px-4 py-16 text-center sm:px-6 lg:px-8 lg:py-20"><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-emerald-400">Start researching</p><h2 className="mx-auto mt-3 max-w-3xl text-4xl font-semibold tracking-tight sm:text-6xl">Your investment research starts here.</h2><p className="mx-auto mt-5 max-w-2xl text-sm leading-7 text-slate-400 sm:text-base">Explore markets, research investments and build your own investment workflow with GNSOne.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href="/stocks" className="rounded-xl bg-emerald-400 px-6 py-3 text-sm font-bold text-[#06101d]">Explore Investments</Link><Link href="/markets" className="rounded-xl border border-white/10 px-6 py-3 text-sm font-semibold">Explore Markets</Link></div></div></section>

      <footer className="border-t border-white/[.07] py-10"><div className="mx-auto grid max-w-7xl gap-8 px-4 sm:px-6 md:grid-cols-4 lg:px-8"><div><Link href="/" className="text-lg font-bold">GNSOne</Link><p className="mt-3 max-w-xs text-xs leading-5 text-slate-600">Research smarter. Invest with clarity.</p></div><div><h3 className="text-xs font-semibold text-slate-300">Explore</h3><div className="mt-3 grid gap-2 text-xs text-slate-600"><Link href="/stocks">Stocks</Link><Link href="/ipo">IPOs</Link><Link href="/mutual-funds">Mutual Funds</Link><Link href="/etfs">ETFs</Link><Link href="/bonds">Bonds</Link><Link href="/markets">Markets</Link></div></div><div><h3 className="text-xs font-semibold text-slate-300">Tools</h3><div className="mt-3 grid gap-2 text-xs text-slate-600"><Link href="/screener">Screener</Link><Link href="/compare">Compare</Link><Link href="/gns-score">GNS Score</Link></div></div><div><h3 className="text-xs font-semibold text-slate-300">Company</h3><div className="mt-3 grid gap-2 text-xs text-slate-600"><Link href="/about">About</Link><Link href="/contact">Contact</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/disclaimer">Disclaimer</Link></div></div></div><div className="mx-auto mt-8 flex max-w-7xl flex-col gap-2 border-t border-white/[.05] px-4 pt-6 text-[11px] text-slate-700 sm:flex-row sm:justify-between sm:px-6 lg:px-8"><span>© 2026 GNSOne</span><span>Market data · Research · Intelligence</span></div></footer>
    </main>
  );
}
