import Link from "next/link";
import { SiteShell, PageTitle, Card } from "@/components/site-shell";
import { getStockBySymbol } from "@/lib/data/stock-repository";

export default async function StockPage({ params }: { params: Promise<{ symbol: string }> }) {
  const { symbol } = await params;
  const stock = await getStockBySymbol(symbol);
  if (!stock) return <SiteShell><PageTitle eyebrow="Stock research" title="Stock not found" description={`No canonical instrument was found for ${symbol.toUpperCase()}.`} /><Link href="/stocks" className="text-sm text-emerald-400">← Browse stocks</Link></SiteShell>;
  const score = stock.score == null ? "—" : Math.round(Number(stock.score));
  return <SiteShell><PageTitle eyebrow="Stock research" title={stock.name} description={`${stock.nse_symbol ? `NSE: ${stock.nse_symbol}` : "BSE instrument"} · Canonical GNSOne research record.`}/><div className="grid gap-5 lg:grid-cols-[1.7fr_1fr]"><Card className="p-6"><p className="text-sm text-slate-500">{stock.nse_symbol ? `NSE · ${stock.nse_symbol}` : `BSE · ${stock.bse_code ?? "—"}`}</p><p className="mt-3 text-4xl font-semibold">{stock.latest_price == null ? "Price unavailable" : `₹${Number(stock.latest_price).toLocaleString("en-IN")}`}</p><p className="mt-2 text-xs text-slate-500">Latest available price · {stock.price_date ?? "No price date"}</p><div className="mt-8 flex h-52 items-center justify-center rounded-xl border border-dashed border-white/10 bg-white/[.02] text-sm text-slate-600">Historical chart will render when price history is available.</div></Card><Card className="p-6"><p className="text-xs uppercase tracking-widest text-slate-500">GNS Score</p><p className="mt-3 text-5xl font-bold text-emerald-300">{score}</p><p className="mt-2 text-sm text-slate-500">Latest calculated score</p></Card></div><div className="mt-5 grid gap-5 md:grid-cols-2"><Card className="p-6"><h2 className="font-semibold">Research modules</h2><div className="mt-5 grid grid-cols-2 gap-2">{["Fundamentals","Valuation","Growth","Shareholding","Technicals","News","Dividends","Corporate actions"].map(x=><button key={x} className="rounded-lg border border-white/[.07] px-3 py-3 text-left text-sm text-slate-300 hover:border-emerald-400/30">{x}<span className="float-right text-slate-600">→</span></button>)}</div></Card><Card className="p-6"><h2 className="font-semibold">Data provenance</h2><p className="mt-3 text-sm leading-6 text-slate-400">This page reads the canonical instrument record and latest available backend analytics. Missing values are shown explicitly rather than fabricated.</p></Card></div></SiteShell>;
}
