import { SiteShell, PageTitle, Card } from "@/components/site-shell";
const config:Record<string,{title:string;eyebrow:string;description:string;items:string[]}>={
sectors:{eyebrow:'Market intelligence',title:'Sectors',description:'Compare sector performance, valuation and GNS leaders.',items:['Financials','Information Technology','Energy','Industrials','Consumer','Healthcare']},
indices:{eyebrow:'Market intelligence',title:'Indices',description:'Explore major Indian equity indices and their constituents.',items:['NIFTY 50','SENSEX','BANK NIFTY','NIFTY IT','NIFTY MIDCAP 100','NIFTY SMALLCAP 100']},
watchlist:{eyebrow:'Personal workspace',title:'Watchlist',description:'Keep your highest-conviction ideas in one place.',items:['Reliance Industries','HDFC Bank','TCS','ICICI Bank']},
portfolio:{eyebrow:'Personal workspace',title:'Portfolio',description:'Track holdings, allocation, performance and risk in one dashboard.',items:['Holdings','Allocation','Performance','Risk']},
alerts:{eyebrow:'Personal workspace',title:'Alerts',description:'Monitor prices, valuation metrics and research signals.',items:['Price alerts','GNS score alerts','Valuation alerts','Earnings alerts']},
research:{eyebrow:'Research',title:'Research',description:'Structured market intelligence built around fundamentals, valuation and risk.',items:['Quality leaders','Growth opportunities','Value opportunities','GNS leaders']},
news:{eyebrow:'Market intelligence',title:'News',description:'Company and market developments organized around your research workflow.',items:['Market news','Company news','Earnings','Corporate updates']},
dividends:{eyebrow:'Income investing',title:'Dividends',description:'Discover dividend history, yield and consistency across Indian equities.',items:['Dividend leaders','Yield watch','Payout history','Dividend calendar']},
'corporate-actions':{eyebrow:'Corporate actions',title:'Corporate Actions',description:'Track dividends, splits, bonuses, buybacks and other company events.',items:['Dividends','Splits','Bonus issues','Buybacks']},
account:{eyebrow:'Account',title:'Account',description:'Manage your profile, preferences and research workspace.',items:['Profile','Preferences','Saved screens','Notifications']},
login:{eyebrow:'GNSOne',title:'Welcome back',description:'Sign in to sync watchlists, screens, portfolios and alerts.',items:['Email address','Password','Continue']},
};
export default async function CatchAll({params}:{params:Promise<{slug:string[]}>}){const {slug}=await params;const key=slug.join('/');const c=config[key]??{eyebrow:'GNSOne',title:key.replaceAll('-',' '),description:'This workspace is part of the GNSOne research platform.',items:['Overview','Data','Analytics','Research']};return <SiteShell><PageTitle eyebrow={c.eyebrow} title={c.title.replace(/^./,x=>x.toUpperCase())} description={c.description}/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{c.items.map((x,i)=><Card key={x} className="p-6"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-emerald-400/10 text-sm font-bold text-emerald-300">{String(i+1).padStart(2,'0')}</div><h2 className="mt-5 font-semibold">{x}</h2><p className="mt-2 text-sm leading-6 text-slate-500">Live data, filters and personalized insights will appear here as the connected data services populate this module.</p><button className="mt-5 text-sm font-semibold text-emerald-400">Explore →</button></Card>)}</div></SiteShell>}
